export const enum HOUSES_NAMES {
    ARRYN = 'House Arryn of the Eyrie',
    BAELISH = 'House Baelish of Harrenhal',
    BARATHEON = 'House Baratheon of Storm\'s End',
    BOLTON = 'House Bolton of the Dreadfort',
    CLEGANE = 'House Clegane',
    FREY = 'House Frey of the Crossing',
    GREYJOY = 'House Greyjoy of Pyke',
    KARSTARK = 'House Karstark of Karhold',
    LANNISTER = 'House Lannister of Casterly Rock',
    MARTELL = 'House Nymeros Martell of Sunspear',
    MORMONT = 'House Mormont of Bear Island',
    STARK = 'House Stark of Winterfell',
    TARGARYEN = 'House Targaryen of King\'s Landing',
    TARLY = 'House Tarly of Horn Hill',
    TARTH = 'House Tarth of Evenfall Hall',
    TULLY = 'House Tully of Riverrun',
    TYRELL = 'House Tyrell of Highgarden',
    UMBER = 'House Umber of the Last Hearth',
}
